Make the crate `no_std`
HorizenLabs/proof-of-sql-verifier pull request #3
Opened 2024-10-03 15:02 UTC by lgiussan

2024-10-04 12:27 UTC, DanieleDiBenedetto approved these changes

2024-10-07 13:19 UTC, la10736 requested changes
More related to ci and build process. Beside that replace `serde_cbor` with some maintained package and check if yu can use the `indexmap` built-in serde support.

2024-10-07 13:19 UTC, la10736 commented on src/bin/generate-sample-proof.rs
> +// You may obtain a copy of the License at
Run this script generate `proof.bin`, `pubs.bin` and `vk.bin` in the root: can you add them to `.gitignore`?

2024-10-07 13:19 UTC, la10736 commented on src/serde.rs
> +                IndexMap::with_capacity_and_hasher(access.size_hint().unwrap_or(0), <_>::default());
Can you use `Default::default()` instead?

2024-10-07 13:19 UTC, la10736 commented on src/serde.rs
> +}
Sure? You really need it? Seams that `indexmap` crate already have a `serde` feature. Did you have tried it?

2024-10-09 13:59 UTC, la10736 approved these changes
GREAT JOB

2024-10-09 13:59 UTC, merged